apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
{%- if cookiecutter.environment_strategy == 'shared' %}
namespace: {{ cookiecutter.cloud_project }}
{%- endif %}
commonLabels:
{%- if cookiecutter.environment_strategy == 'dedicated' %}
  app: {{ cookiecutter.project_slug }}
{%- endif %}
  component: database
{%- if cookiecutter.environment_strategy == 'shared' %}
{%- endif %}
resources:
- statefulset.yaml
- secret.yaml
- service.yaml
