apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
{%- if cookiecutter.environment_strategy == 'dedicated' %}
  app: {{ cookiecutter.project_slug }}
{%- endif %}
  component: database
{%- if cookiecutter.environment_strategy == 'shared' %}
namespace: {{ cookiecutter.project_slug }}
{%- endif %}
resources:
- deployment.yaml
- secret.yaml
- service.yaml
