apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  environment: production
{%- if cookiecutter.environment_strategy == 'shared' %}
  app: {{ cookiecutter.project_slug }}-production
nameSuffix: -production
{%- else %}
namespace: {{ cookiecutter.project_slug }}-production
{%- endif %}
patchesStrategicMerge:
- deployment.yaml
