# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

language: python
python:
  - 3.5
  - 3.6
  - pypy3

stages:
  - lint
  - test

jobs:
  include:
    - { stage: lint, python: 3.6, env: TOXENV=flake8 }
    - { stage: lint, python: 3.6, env: TOXENV=pylint }
    - { stage: test, python: 3.7, dist: xenial, sudo: true }
    - { stage: test, python: 3.6, env: TOXENV=behave }

install: pip install tox-travis
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
