# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

sudo: false
language: python
python: 3.6

env:
  matrix:  # $ tox -l | xargs -I ARG echo '    - TOXENV=ARG'
    - TOXENV=flake8
    - TOXENV=pylint
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=pypy
    - TOXENV=behave

install: pip install tox
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
