# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - pypy3

matrix:
  include:
    - { python: 3.6, env: TOXENV=flake8 }
    - { python: 3.6, env: TOXENV=pylint }
    - { python: 3.6, env: TOXENV=behave }

install: pip install tox-travis
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
