# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

os: linux
dist: bionic
language: python
python:
- 3.6
- 3.7
- 3.8
- pypy3

stages:
- lint
- test

jobs:
  include:
  - { stage: lint, python: 3.7, env: TOXENV=flake8 }
  - { stage: lint, python: 3.7, env: TOXENV=pylint }
  - { stage: lint, python: 3.7, env: TOXENV=bandit }
  - { stage: test, python: 3.7, env: TOXENV=behave }

  allow_failures:
  - env: TOXENV=bandit

install: pip install tox-travis
script: tox
