{% if cookiecutter.checks %}{% for env in cookiecutter.checks.split(",") | unique %}
{{ env }}:
  extends: .check
  script: {% if cookiecutter.framework in ['Django', 'Flask'] -%}
    tox -e {{ env }}
      {%- elif cookiecutter.framework in ['Symfony', 'TYPO3'] -%}
    echo "This should run {{ env }}"
      {%- elif cookiecutter.framework in ['SpringBoot'] -%}
    echo "This should run {{ env }}"
      {%- endif %}
{% endfor %}{% endif -%}
