  {%- for env in cookiecutter.checks.split(",") %}
  {%- if cookiecutter.framework in ['Django', 'Flask'] %}
  - { stage: lint, python: 3.7, env: TOXENV={{ env }} }
  {%- elif cookiecutter.framework in ['Symfony', 'TYPO3'] %}
  - { stage: lint, script: echo "This should run {{ env }}" }
  {%- elif cookiecutter.framework in ['SpringBoot'] %}
  - { stage: lint, script: echo "This should run {{ env }}" }
  {%- endif %}
  {%- endfor -%}
