apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
{%- if cookiecutter.environment_strategy == 'shared' %}
nameSuffix: -development
{%- else %}
namespace: {{ cookiecutter.project_slug }}-development
{%- endif %}
{%- if cookiecutter.vcs_platform == 'GitLab.com' and cookiecutter.environment_strategy == 'shared' %}
commonAnnotations:
  app.gitlab.com/app: {{ cookiecutter.vcs_account|lower }}-{{ cookiecutter.project_slug }}
  app.gitlab.com/env: development
{%- endif %}
commonLabels:
{%- if cookiecutter.environment_strategy == 'shared' %}
  app: {{ cookiecutter.project_slug }}-development
{%- endif %}
  environment: development
resources:
- ../../base
