apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  environment: development
{%- if cookiecutter.environment_strategy == 'shared' %}
  app: {{ cookiecutter.project_slug }}-development
nameSuffix: -development
{%- else %}
namespace: {{ cookiecutter.project_slug }}-development
{%- endif %}
