[tool.bandit]
exclude = [".cache",".git",".idea",".tox",".vscode","build","dist","docs","tests"]

[tool.black]
color = true

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
source = ["application"]

[tool.coverage.xml]
output = "tests/coverage-report.xml"

[tool.isort]
color_output = true
profile = "black"

[tool.pylint.master]
{%- if cookiecutter.framework == 'Django' %}
load-plugins = "pylint_django"
{%- endif %}
output-format = "colorized"

[tool.pylint.messages_control]
disable = []

[tool.pytest.ini_options]
addopts = "--color=yes --doctest-modules {% if cookiecutter.framework == 'Django' %}--ignore=application/urls.py --ignore=application/wsgi.py {% endif %}--ignore=tests/acceptance/steps --junitxml=tests/unittests-report.xml --verbose"
{%- if cookiecutter.framework == 'Django' %}
DJANGO_SETTINGS_MODULE = "application.settings"
FAIL_INVALID_TEMPLATE_VARS = true
python_files = ["tests.py","test_*.py","*_tests.py"]
{%- endif %}
