{% if cookiecutter.tests %}{% for env in cookiecutter.tests.split(",") | unique %}
{{ env }}:
  extends: .test
  script: {% if cookiecutter.framework in ['Django', 'Flask'] -%}
    tox -e {{ env }}
      {%- elif cookiecutter.framework in ['SpringBoot'] -%}
    mvn {{ env }}
      {%- endif %}
{% endfor %}{% endif -%}
