
  - parallel: &tests
    {%- for env in cookiecutter.tests.split(",") %}
    - step:
        name: {{ env|replace('py36','Python 3.6')|replace('py37','Python 3.7')|replace('py38','Python 3.8')|replace('pypy3','PyPy 3')|replace('behave','Behave') }}
        script:
        {%- if cookiecutter.framework in ['Django', 'Flask'] %}
        - tox -e {{ env }}
        {%- elif cookiecutter.framework in ['Symfony', 'TYPO3'] %}
        - echo "This should run {{ env }}"
        {%- elif cookiecutter.framework in ['SpringBoot'] %}
        - echo "This should run {{ env }}"
        {%- endif %}
    {%- endfor -%}
