apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  environment: integration
{%- if cookiecutter.environment_strategy == 'shared' %}
nameSuffix: -integration
{%- endif %}
