# Painless deployment with Bitbucket Pipelines.
# Visit the docs at https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/

pipelines:
  default:
  - parallel:
    - step:
        name: Lint manifests
        image: docker.io/garethr/kubeval:latest
        script:
        - /kubeval --strict --ignore-missing-schemas **/*.yaml
