apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-examples
spec:
  schedule: ""
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args: ARGS
          restartPolicy: Never
