# Painless deployment with GitLab CI.
# Visit the docs at https://docs.gitlab.com/ce/ci/

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: registry.appuio.ch
  DOCKER_HOST: tcp://docker:2375
  OPENSHIFT_CONSOLE: https://console.appuio.ch
  OPENSHIFT_PROJECT_STAGING: example-staging
  OPENSHIFT_PROJECT_PROD: example-prod
  APP_NAME: example

services:
  - name: docker:dind

{#- (stages follow now, after one empty line) #}
{% include '_/ci-services/lint-stage/%s' % cookiecutter.ci_service -%}
{% include '_/ci-services/test-stage/%s' % cookiecutter.ci_service -%}
{% include '_/ci-services/build-stage/%s' % cookiecutter.ci_service -%}
{% include '_/ci-services/deploy-stage/%s' % cookiecutter.ci_service -%}
