# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

sudo: false
language: python
python: 3.6

env:
  matrix:  # $ tox -l | xargs -I ARG echo '    - TOXENV=ARG'
    {%- for env in cookiecutter.tests.split(',') %}
    - TOXENV={{ env }}
    {%- endfor %}

install: pip install tox
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
