# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

dist: trusty
sudo: false
language: python
python: 3.6

env:
  matrix:  # $ tox -l | xargs -I ARG echo '    - TOXENV=ARG'
    {%- for env in cookiecutter.tests.split(',') %}
    - TOXENV={{ env }}
    {%- endfor %}

before_install:  # temporary fix for https://github.com/travis-ci/travis-ci/issues/4990#issuecomment-297863117
  - if [[ $TOXENV = py35 && -f ~/virtualenv/python3.5/bin/activate ]]; then source ~/virtualenv/python3.5/bin/activate; fi
install: pip install tox
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
