# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

os: linux
language: python
python:
{%- for env in cookiecutter.tests.split(",") if env not in ["behave", "py37"] %}
- {{ env|replace('py35','3.5')|replace('py36','3.6')|replace('py37','3.7')|replace('py38','3.8') }}
{%- endfor %}

stages:
- lint
- test

jobs:
  include:
{%- include '_/ci-services/definitions/%s' % cookiecutter.ci_service -%}
{% include '_/ci-services/lint-stage/%s' % cookiecutter.ci_service -%}
{% include '_/ci-services/test-stage/%s' % cookiecutter.ci_service -%}
{% include '_/ci-services/build-stage/%s' % cookiecutter.ci_service -%}
{% include '_/ci-services/deploy-stage/%s' % cookiecutter.ci_service %}

install: pip install tox-travis
script: tox
