# Painless deployment with Codeship.
# Visit the docs at https://documentation.codeship.com/pro/getting-started/services/#services-file-setup--configuration

version: '2'

services:
  app:
    image: painless/tox:multi
    volumes:
    - .:/app
