# Painless deployment with Codeship.
# Visit the docs at https://documentation.codeship.com/pro/getting-started/services/#services-file-setup--configuration

version: '2'

services:
  app:
    image: {% if cookiecutter.framework in ['Django', 'Flask'] -%}
      painless/tox:multi
        {%- elif cookiecutter.framework in ['Symfony', 'TYPO3'] -%}
      painless/composer
        {%- elif cookiecutter.framework in ['SpringBoot'] -%}
      openjdk:8-jdk-alpine
        {%- endif %}
    volumes:
    - .:/app
