apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ cookiecutter.cloud_project }}{% if cookiecutter.environment_strategy == 'dedicated' %}-production{% endif %}
{%- if cookiecutter.vcs_platform == 'GitLab.com' %}
commonAnnotations:
  app.gitlab.com/app: {{ cookiecutter.vcs_account|lower }}-{{ cookiecutter.vcs_project|lower }}
  app.gitlab.com/env: production
{%- endif %}
commonLabels:
  environment: production
resources:
- ../../base
