name: Checks

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PY_COLORS: "1"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - flake8
        - isort
        - pylint
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install prerequisites
      run: python -m pip install --upgrade setuptools pip wheel tox
    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
