name: Checks

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PY_COLORS: '1'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - ruff
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install prerequisites
      run: python -m pip install tox wheel --disable-pip-version-check
    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
