name: Tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PY_COLORS: '1'

jobs:
  unit:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - pypy-3.9
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install prerequisites
      run: python -m pip install tox-gh-actions wheel --disable-pip-version-check
    - name: Run tests
      run: tox
  behave:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install prerequisites
      run: python -m pip install tox wheel --disable-pip-version-check
    - name: Run behave
      run: tox -e behave
