apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: application-job-backup
spec:
  schedule: "59 1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: application
            image: IMAGE
{%- if cookiecutter.framework == 'Django' %}
            command: ['/bin/bash', '-c']
            args:
              - python manage.py dumpdata -o backups/db.json ;
              - cat backups/db.json
            envFrom:
            - secretRef:
                name: application
{%- else %}
            command: ['echo', 'hello world']
{%- endif %}
          restartPolicy: Never
