apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-example
spec:
  schedule: "1 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: application
            image: IMAGE
{%- if cookiecutter.framework == 'Django' %}
            command: ['python', 'manage.py', 'dumpdata']
            envFrom:
            - secretRef:
                name: application
{%- else %}
            command: ['echo', 'hello world']
{%- endif %}
          restartPolicy: Never
