apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
roleRef:
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: gitlab-ci
  namespace: {{ cookiecutter.project_slug }}{% if cookiecutter.environment_strategy == 'dedicated' %}-production{% endif %}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit
roleRef:
  kind: ClusterRole
  name: edit
subjects:
- kind: User
  name: {{ cookiecutter.container_platform_account }}
