apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
{%- if cookiecutter.environment_strategy == 'shared' %}
nameSuffix: -integration
{%- else %}
namespace: {{ cookiecutter.project_slug }}-integration
{%- endif %}
{%- if cookiecutter.vcs_platform == 'GitLab.com' and cookiecutter.environment_strategy == 'shared' %}
commonAnnotations:
  app.gitlab.com/app: {{ cookiecutter.vcs_account|lower }}-{{ cookiecutter.project_slug }}
  app.gitlab.com/env: integration
{%- endif %}
commonLabels:
{%- if cookiecutter.environment_strategy == 'shared' %}
  app: {{ cookiecutter.project_slug }}-integration
{%- endif %}
  environment: integration
configMapGenerator:
- name: application
  behavior: merge
  envs:
  - application.env
resources:
- ../../base
