apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ cookiecutter.cloud_project }}{% if cookiecutter.environment_strategy == 'dedicated' %}-integration{% endif %}
{%- if cookiecutter.vcs_platform == 'GitLab.com' %}
commonAnnotations:
  app.gitlab.com/app: {{ cookiecutter.vcs_account|lower }}-{{ cookiecutter.vcs_project|lower }}
  app.gitlab.com/env: integration
{%- endif %}
commonLabels:
  environment: integration
configMapGenerator:
- name: application
  behavior: merge
  envs:
  - application.env
resources:
- ../../base
